version = 1

[[annotations]]
path = [
    ".benchmarks/**",
    ".dockerignore",
    ".gitignore",
    ".python-version",
    ".releaserc.json",
    "CITATION.cff",
    "REUSE.toml",
    "benchmarks/.benchmarks/**",
    "benchmarks/output/plots/*.png",
    "docs/package-lock.json",
    "docs/package.json",
    "docs/tsconfig.json",
    "pyproject.toml",
    "tests/reader/*.nt",
    "tests/resources/*.json",
    "uv.lock",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "notebooks/*.ipynb"
SPDX-FileCopyrightText = "2022 Simone Persiani <iosonopersia@gmail.com>"
SPDX-License-Identifier = "ISC"

[[annotations]]
path = "oc_ocdm/resources/shacle.ttl"
SPDX-FileCopyrightText = "2023 Arcangelo Massari <arcangelo.massari@unibo.it>"
SPDX-License-Identifier = "ISC"
