# SPDX-FileCopyrightText: 2022-2026 Arcangelo Massari <arcangelo.massari@unibo.it>
#
# SPDX-License-Identifier: ISC

name: Run tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  CheckCoverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v6

    - name: Install UV
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Install Python
      run: uv python install

    - name: Install dependencies
      run: uv sync --locked --all-groups

    - name: Run tests with coverage
      run: |
        uv run coverage run --rcfile=tests/coverage/.coveragerc
        uv run coverage xml
        uv run coverage report

    - name: Generate HTML coverage report
      if: matrix.python-version == '3.12'
      run: uv run coverage html -d htmlcov

    - name: Generate coverage badge
      if: matrix.python-version == '3.12'
      run: |
        uv run genbadge coverage -i coverage.xml -o htmlcov/coverage-badge.svg

    - name: Upload coverage report to GitHub Pages
      if: matrix.python-version == '3.12' && github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v4
      with:
        path: htmlcov/

    - uses: actions/upload-artifact@v7
      with:
          name: coverage-artifact-${{ matrix.python-version }}
          path: tests/coverage/

  DeployPages:
    needs: CheckCoverage
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
